/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SubsidyLedger {
  export type DistributionStruct = {
    farmerId: AddressLike;
    itemType: string;
    itemName: string;
    quantity: BigNumberish;
    unit: string;
    distributorId: AddressLike;
    timestamp: BigNumberish;
  };

  export type DistributionStructOutput = [
    farmerId: string,
    itemType: string,
    itemName: string,
    quantity: bigint,
    unit: string,
    distributorId: string,
    timestamp: bigint
  ] & {
    farmerId: string;
    itemType: string;
    itemName: string;
    quantity: bigint;
    unit: string;
    distributorId: string;
    timestamp: bigint;
  };
}

export interface SubsidyLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addDistributor"
      | "authorizedDistributors"
      | "farmerDistributions"
      | "getDistributionCount"
      | "getDistributions"
      | "owner"
      | "recordDistribution"
      | "removeDistributor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DistributionRecorded"
      | "DistributorAdded"
      | "DistributorRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addDistributor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedDistributors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "farmerDistributions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDistributionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDistributions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordDistribution",
    values: [AddressLike, string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeDistributor",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedDistributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "farmerDistributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDistributionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDistributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeDistributor",
    data: BytesLike
  ): Result;
}

export namespace DistributionRecordedEvent {
  export type InputTuple = [
    farmerId: AddressLike,
    distributorId: AddressLike,
    itemType: string,
    quantity: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    farmerId: string,
    distributorId: string,
    itemType: string,
    quantity: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    farmerId: string;
    distributorId: string;
    itemType: string;
    quantity: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributorAddedEvent {
  export type InputTuple = [distributor: AddressLike];
  export type OutputTuple = [distributor: string];
  export interface OutputObject {
    distributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributorRemovedEvent {
  export type InputTuple = [distributor: AddressLike];
  export type OutputTuple = [distributor: string];
  export interface OutputObject {
    distributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SubsidyLedger extends BaseContract {
  connect(runner?: ContractRunner | null): SubsidyLedger;
  waitForDeployment(): Promise<this>;

  interface: SubsidyLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addDistributor: TypedContractMethod<
    [distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedDistributors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  farmerDistributions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, string, string, bigint] & {
        farmerId: string;
        itemType: string;
        itemName: string;
        quantity: bigint;
        unit: string;
        distributorId: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getDistributionCount: TypedContractMethod<
    [farmerId: AddressLike],
    [bigint],
    "view"
  >;

  getDistributions: TypedContractMethod<
    [farmerId: AddressLike],
    [SubsidyLedger.DistributionStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordDistribution: TypedContractMethod<
    [
      farmerId: AddressLike,
      itemType: string,
      itemName: string,
      quantity: BigNumberish,
      unit: string
    ],
    [void],
    "nonpayable"
  >;

  removeDistributor: TypedContractMethod<
    [distributor: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addDistributor"
  ): TypedContractMethod<[distributor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedDistributors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "farmerDistributions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, string, string, bigint] & {
        farmerId: string;
        itemType: string;
        itemName: string;
        quantity: bigint;
        unit: string;
        distributorId: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDistributionCount"
  ): TypedContractMethod<[farmerId: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDistributions"
  ): TypedContractMethod<
    [farmerId: AddressLike],
    [SubsidyLedger.DistributionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordDistribution"
  ): TypedContractMethod<
    [
      farmerId: AddressLike,
      itemType: string,
      itemName: string,
      quantity: BigNumberish,
      unit: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeDistributor"
  ): TypedContractMethod<[distributor: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DistributionRecorded"
  ): TypedContractEvent<
    DistributionRecordedEvent.InputTuple,
    DistributionRecordedEvent.OutputTuple,
    DistributionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "DistributorAdded"
  ): TypedContractEvent<
    DistributorAddedEvent.InputTuple,
    DistributorAddedEvent.OutputTuple,
    DistributorAddedEvent.OutputObject
  >;
  getEvent(
    key: "DistributorRemoved"
  ): TypedContractEvent<
    DistributorRemovedEvent.InputTuple,
    DistributorRemovedEvent.OutputTuple,
    DistributorRemovedEvent.OutputObject
  >;

  filters: {
    "DistributionRecorded(address,address,string,uint256,uint256)": TypedContractEvent<
      DistributionRecordedEvent.InputTuple,
      DistributionRecordedEvent.OutputTuple,
      DistributionRecordedEvent.OutputObject
    >;
    DistributionRecorded: TypedContractEvent<
      DistributionRecordedEvent.InputTuple,
      DistributionRecordedEvent.OutputTuple,
      DistributionRecordedEvent.OutputObject
    >;

    "DistributorAdded(address)": TypedContractEvent<
      DistributorAddedEvent.InputTuple,
      DistributorAddedEvent.OutputTuple,
      DistributorAddedEvent.OutputObject
    >;
    DistributorAdded: TypedContractEvent<
      DistributorAddedEvent.InputTuple,
      DistributorAddedEvent.OutputTuple,
      DistributorAddedEvent.OutputObject
    >;

    "DistributorRemoved(address)": TypedContractEvent<
      DistributorRemovedEvent.InputTuple,
      DistributorRemovedEvent.OutputTuple,
      DistributorRemovedEvent.OutputObject
    >;
    DistributorRemoved: TypedContractEvent<
      DistributorRemovedEvent.InputTuple,
      DistributorRemovedEvent.OutputTuple,
      DistributorRemovedEvent.OutputObject
    >;
  };
}
